branches:
  only:
  - master
sudo: false
language: node_js
node_js:
- '14'
install:
- npm i npminstall && npminstall
script:
- npm run ci
after_script:
- npminstall codecov && codecov
services:
- mongodb
- redis-server
env:
  global:
  - ENCRYPTION_LABEL: 
  - secure: 
  - secure: 
